# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: nookx
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTU1NWU2MmQ2Y2U0Zjc1YzMxMjAzOWFhOTg5ZDA1YjkyMjhjZmVhNDg1ZTk0ZjAwNzdiODA2YzM5OGVlOTI3MDEyM2Q3MmRhOTlhMDk2ZGE3NTJhMjUzMThmOGQ2Y2JkZGNlMGE1ODQ3NTdlZjBiZjU0MGJjYjRjNzI1NjQxYzk=
