package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileCollectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionAllPropertiesEquals(ProfileCollection expected, ProfileCollection actual) {
        assertProfileCollectionAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileCollectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionAllUpdatablePropertiesEquals(ProfileCollection expected, ProfileCollection actual) {
        assertProfileCollectionUpdatableFieldsEquals(expected, actual);
        assertProfileCollectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionAutoGeneratedPropertiesEquals(ProfileCollection expected, ProfileCollection actual) {
        assertThat(actual)
            .as("Verify ProfileCollection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionUpdatableFieldsEquals(ProfileCollection expected, ProfileCollection actual) {
        assertThat(actual)
            .as("Verify ProfileCollection relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionUpdatableRelationshipsEquals(ProfileCollection expected, ProfileCollection actual) {
        assertThat(actual)
            .as("Verify ProfileCollection relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()));
    }
}
