package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurrencyAsserts {

    public static void assertCurrencyAllPropertiesEquals(Currency expected, Currency actual) {
        assertCurrencyAutoGeneratedPropertiesEquals(expected, actual);
        assertCurrencyAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertCurrencyAllUpdatablePropertiesEquals(Currency expected, Currency actual) {
        assertCurrencyUpdatableFieldsEquals(expected, actual);
        assertCurrencyUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertCurrencyAutoGeneratedPropertiesEquals(Currency expected, Currency actual) {
        assertThat(actual)
            .as("Verify Currency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertCurrencyUpdatableFieldsEquals(Currency expected, Currency actual) {
        assertThat(actual)
            .as("Verify Currency relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()));
    }

    public static void assertCurrencyUpdatableRelationshipsEquals(Currency expected, Currency actual) {
        // empty method
    }
}
